"""
Decoy generation for the chaff layer.

A PDF's ToUnicode CMap may map one CID to a *string*, not just a character. That
single fact removes the constraint that dominated the first prototype: the decoy no
longer has to match the true text word-for-word in length, so it does not need to be
generated by a constrained-decoding model. It can be ordinary human prose.

Each drawn glyph is assigned a consecutive chunk of the decoy, and the extracted text
is the concatenation of those chunks -- exactly the decoy, verbatim. Six glyphs can
report a full sentence.

The decoy is assembled by keyed recombination of a cover corpus: sentences are
permuted under HMAC(recipient, block) and concatenated. The result is fluent, is
different for every recipient, and therefore doubles as a coarse secondary
fingerprint (log2(n!) bits of ordering) behind the primary kerning channel.

A cover corpus must contain the SPECIFICS ITS GENRE WOULD CONTAIN -- dates, amounts,
percentages, organisation and person names. The first corpora here were carefully
generic and that was a mistake, for two reasons. An ingestion filter looking for
anomalies would notice a document with no entities in it at all, which is a strange
property for minutes or an inventory to have. And more importantly, a decoy without
specifics merely gives a pipeline nothing; a decoy with plausible ones gives it
CONFIDENT WRONG ANSWERS, which is a far stronger outcome -- the extracted figure goes
into the index, the summary, the answer to a question nobody realises was about the
wrong document.

Every specific in a cover must be fictional and must not collide with anything in a real
document, or the "no distinctive term survives" property becomes false by accident. The
`verify` command exists to check that on real output rather than trusting it.
"""
from __future__ import annotations
import hashlib
import hmac
import os
import re

COVER_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "covers")


def available_covers() -> list[str]:
    if not os.path.isdir(COVER_DIR):
        return []
    return sorted(f[:-4] for f in os.listdir(COVER_DIR) if f.endswith(".txt"))


def load_cover(name: str) -> list[str]:
    path = os.path.join(COVER_DIR, name + ".txt")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"unknown cover {name!r}; available: {', '.join(available_covers())}")
    with open(path, encoding="utf-8") as fh:
        raw = fh.read()
    sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", raw) if s.strip()]
    return [re.sub(r"\s+", " ", s) for s in sentences]


class Decoy:
    """A keyed, effectively unbounded stream of fluent cover prose."""

    def __init__(self, cover: str, recipient_id: str):
        self.sentences = load_cover(cover)
        self.key = hashlib.sha256(
            f"cloister-decoy-v2|{cover}|{recipient_id}".encode()).digest()
        self._block = 0
        self._buf = ""

    def _permute(self, block: int) -> str:
        """A keyed permutation of the cover sentences for this block."""
        n = len(self.sentences)
        order = sorted(
            range(n),
            key=lambda i: hmac.new(self.key, f"{block}:{i}".encode(),
                                   hashlib.sha256).digest())
        return " ".join(self.sentences[i] for i in order) + " "

    def _fill(self, nchars: int):
        while len(self._buf) < nchars + 64:
            self._buf += self._permute(self._block)
            self._block += 1

    def take(self, nchars: int) -> str:
        self._fill(nchars)
        out, self._buf = self._buf[:nchars], self._buf[nchars:]
        return out

    def segment(self, nglyphs: int) -> str:
        """
        Whole cover words totalling at least `nglyphs` characters, so the reported
        text for one drawn word is composed of real words rather than a slice cut
        mid-word. Because a CID may report several characters, the decoy word does
        not have to be the same length as the word it hides behind -- that is the
        constraint multi-character ToUnicode removes.
        """
        self._fill(max(nglyphs * 3, 96))
        parts, used = [], 0
        while used < nglyphs:
            sp = self._buf.find(" ")
            if sp < 0:
                sp = len(self._buf) - 1
                self._fill(nglyphs * 3)
                continue
            word, self._buf = self._buf[:sp], self._buf[sp + 1:]
            if word:
                parts.append(word)
                used += len(word) + (1 if len(parts) > 1 else 0)
            self._fill(max(nglyphs * 3, 96))
        return " ".join(parts)


def chunk_for_glyphs(text: str, nglyphs: int) -> list[str]:
    """
    Split `text` into exactly `nglyphs` consecutive non-empty chunks, sizes as even
    as possible, preferring to break at spaces so the reported text keeps its word
    boundaries where a reader would expect them.
    """
    if nglyphs <= 0:
        return []
    if len(text) < nglyphs:
        text = (text * (nglyphs // max(1, len(text)) + 2))[:nglyphs]
    base, extra = divmod(len(text), nglyphs)
    bounds, pos = [], 0
    for i in range(nglyphs):
        size = base + (1 if i < extra else 0)
        pos += size
        bounds.append(pos)
    bounds[-1] = len(text)
    # nudge each boundary to the nearest following space, without starving a chunk
    for i in range(len(bounds) - 1):
        lo = bounds[i]
        hi = min(bounds[i] + 3, bounds[i + 1] - 1)
        for j in range(lo, hi + 1):
            if j < len(text) and text[j] == " ":
                bounds[i] = j + 1
                break
    out, prev = [], 0
    for b in bounds:
        b = max(b, prev + 1)
        out.append(text[prev:b])
        prev = b
    return out
